public static void main (String[] args) {
    int 
    power_1,    
    power_2,    
    power_3,    
    power_4,    
    power_5,    
    power_6,    
    power_7,    
    power_8,    
    power_9,    
    power_10,    
    power_11,    
    power_12,    
    power_13,        
    power_14,    
    power_15,    
    power_16;

    System.out.println(power_1);
    System.out.println(power_2);
    System.out.println(power_3);
    System.out.println(power_4);
    System.out.println(power_5);
    System.out.println(power_6);
    System.out.println(power_7);
    System.out.println(power_8);
    System.out.println(power_9);
    System.out.println(power_10);
    System.out.println(power_11);
    System.out.println(power_12);
    System.out.println(power_13);
    System.out.println(power_14);
    System.out.println(power_15);
    System.out.println(power_16);
}